// Code generated by "stringer -type=MutexState"; DO NOT EDIT

package common

import "fmt"

const _MutexState_name = "StateReleasedStateWantedStateHeld"

var _MutexState_index = [...]uint8{0, 13, 24, 33}

func (i MutexState) String() string {
	if i < 0 || i >= MutexState(len(_MutexState_index)-1) {
		return fmt.Sprintf("MutexState(%d)", i)
	}
	return _MutexState_name[_MutexState_index[i]:_MutexState_index[i+1]]
}
